### ISSUE TITLE
[tracker] windows support

### ISSUE THREAD

**Issue by serkonda7** [tiabeast/bait#124]
- [x] make.bat
- [x] symlink
- [x] Run full CI on windows
- [x] Run rosetta-bait CI on windows
- [x] Update setup-bait
- [x] Documentation (readme)
